x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:
  app:
    image: file-server:latest
    build:
      context: .
    environment:
      upload-folder: /uploads
      <<: *shared_environment
    volumes:
      - type: bind
        source: ./upload
        target: /uploads
    ports:
      - '8080:80'
